services:
  mediamtx:
    image: bluenviron/mediamtx:1.12.3-ffmpeg
    container_name: mediamtx
    restart: always
    ports:
      - "1935:1935"
      - "8554:8554"
      - "8888:8888"
      - "8889:8889"
      - "554:554"
      - "554:554/udp"
      - "9997:9997"
      - "8189:8189/udp"
    volumes:
      - ./config/mediamtx.yml:/mediamtx.yml
      - ./recordings:/recordings
    networks:
      - sas
    env_file:
      - ./.env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    # image: sas-baturaja110:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      AUTH_URL: ${AUTH_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      NODE_ENV: ${NODE_ENV}
      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS}
      DATABASE_URL: ${DATABASE_URL}
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      NEXT_PUBLIC_MEDIAMTX_URL: ${NEXT_PUBLIC_MEDIAMTX_URL}
      NEXT_PUBLIC_MEDIAMTX_RTSP: ${NEXT_PUBLIC_MEDIAMTX_RTSP}
      NEXT_PUBLIC_MAPS: ${NEXT_PUBLIC_MAPS}
      NEXT_PUBLIC_MEDIAMTX_API: ${NEXT_PUBLIC_MEDIAMTX_API}      
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      MEDIAMTX_STUN: ${MEDIAMTX_STUN}
      MEDIAMTX_ADDITIONAL_HOSTS: ${MEDIAMTX_ADDITIONAL_HOSTS}
      PATH_HOST_APP: ${PATH_HOST_APP}
    networks:
      - sas
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/app/config
      - ./recordings:/app/recordings

networks:
  sas:
    ipam:
      driver: default
      config:
        - subnet: "172.1.255.0/24"