version: '3.8'  # ubah ke versi yang lebih baru supaya support network & label

services:
  mediamtx:
    image: aler9/rtsp-simple-server
    container_name: mediamtx
    restart: always
    ports:
      - "1935:1935"        
      - "8554:8554"       
      - "8189:8189/udp"    
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.constraint-label=traefik-public"
      - "traefik.http.routers.mediamtx.rule=Host(`mediamtx.spero-lab.id`)"
      - "traefik.http.routers.mediamtx.entrypoints=http"
      - "traefik.http.routers.mediamtx-https.rule=Host(`mediamtx.spero-lab.id`)"
      - "traefik.http.routers.mediamtx-https.entrypoints=https"
      - "traefik.http.routers.mediamtx-https.tls.certresolver=le"
      - "traefik.http.routers.mediamtx-https.tls=true"
      - "traefik.http.services.mediamtx-https.loadbalancer.server.port=3001"