services:
  ffmpeg:
    container_name: ffmpeg_sas
    image: jrottenberg/ffmpeg:4.4-ubuntu
    volumes:
      - ./public/stream:/app/public/stream
      - ./public/record:/app/public/record
    entrypoint: ["sleep", "infinity"]
    network_mode: host

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: app
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NODE_ENV: ${NODE_ENV}
  #     AUTH_URL: ${AUTH_URL}
  #     AUTH_SECRET: ${AUTH_SECRET}
  #     BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS}
  #     DATABASE_URL: ${DATABASE_URL}
  #     NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
  #     MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
  #     MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
  #     MINIO_ENDPOINT: ${MINIO_ENDPOINT}
  #     MINIO_PUBLIC_URL: ${MINIO_PUBLIC_URL}
  #     MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./public/uploads:/app/public/uploads