version: '1.0'

services:
  mediamtx:
    image: aler9/rtsp-simple-server
    container_name: mediamtx
    restart: always
    ports:
      - "1935:1935"
      - "8554:8554"
      - "8888:8888"
      - "8889:8889"
      - "8189:8189/udp"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      AUTH_URL: ${AUTH_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS}
      DATABASE_URL: ${DATABASE_URL}
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
