version: '3.8'  # ubah ke versi yang lebih baru supaya support network & label

services:
  mediamtx:
    image: aler9/rtsp-simple-server
    container_name: mediamtx
    restart: always
    ports:
      - "1935:1935"        
      - "8554:8554"       
      - "8189:8189/udp"    
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.constraint-label=traefik-public"
      - "traefik.http.routers.mediamtx.rule=Host(`mediamtx.spero-lab.id`)"
      - "traefik.http.routers.mediamtx.entrypoints=http"
      - "traefik.http.routers.mediamtx-https.rule=Host(`mediamtx.spero-lab.id`)"
      - "traefik.http.routers.mediamtx-https.entrypoints=https"
      - "traefik.http.routers.mediamtx-https.tls.certresolver=le"
      - "traefik.http.routers.mediamtx-https.tls=true"
      - "traefik.http.services.mediamtx-https.loadbalancer.server.port=3001"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sas
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.constraint-label=traefik-public"
      - "traefik.http.routers.sas.rule=Host(`sas-kemhan.spero-lab.id`)"
      - "traefik.http.routers.sas.entrypoints=http"
      - "traefik.http.routers.sas-https.rule=Host(`sas-kemhan.spero-lab.id`)"
      - "traefik.http.routers.sas-https.entrypoints=https"
      - "traefik.http.routers.sas-https.tls.certresolver=le"
      - "traefik.http.routers.sas-https.tls=true"
      - "traefik.http.services.sas-https.loadbalancer.server.port=3001"
    environment:
      NODE_ENV: ${NODE_ENV}
      AUTH_URL: ${AUTH_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS}
      DATABASE_URL: ${DATABASE_URL}
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_PUBLIC_URL: ${MINIO_PUBLIC_URL}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./public/uploads:/app/public/uploads
