version: '3.8'  # ubah ke versi yang lebih baru supaya support network & label

services:
  mediamtx:
    image: aler9/rtsp-simple-server
    container_name: mediamtx
    restart: always
    ports:
      - "1935:1935"        
      - "8554:8554"       
      - "8189:8189/udp"    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mediamtx.rule=Host(`mediamtx.spero-lab.id`)"
      - "traefik.http.routers.mediamtx.entrypoints=websecure"
      - "traefik.http.routers.mediamtx.tls.certresolver=letsencrypt"
    networks:
      - coolify

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`sas-kemhan.spero-lab.id`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"
    environment:
      NODE_ENV: ${NODE_ENV}
      AUTH_URL: ${AUTH_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS}
      DATABASE_URL: ${DATABASE_URL}
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_PUBLIC_URL: ${MINIO_PUBLIC_URL}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./public/uploads:/app/public/uploads
    networks:
      - coolify

networks:
  coolify:
    external: true
