import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/common/utils/Provider";
import AuthWrapper from "@/common/utils/AuthWrapper";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CodingRafi",
  description: "Generated by CodingRafi",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
        <SessionProvider>
          <AuthWrapper>
            <Providers>{children}</Providers>
          </AuthWrapper>
        </SessionProvider>
      </body>
    </html>
  );
}
